### ISSUE TITLE
Формирование текстового описания sql запроса.

### ISSUE THREAD

**Issue by MiniKrishna** [moevm/mse_db_gen_tasks#79]
Написать класс/функцию преобразующую sql запрос в описание на естественном языке. Возможности на этой итерации должны соответствовать генератору запросов из задачи - https://github.com/moevm/mse_db_gen_tasks/issues/44.
В дополнение написать пару тестов к новому функционалу.
Результат: возможность получать текстовое описание sql запроса

**Comment by esiole** [comment]
Выполнено в PR #90
